cc2538-bsl.py
On certain Mac platforms, toggling UART pins to enter the bootloader
were happening too fast, causing the CC2538 to not detect that it should
enter the bootloader and ending with the script not working. Adding this
delay takes care of that problem while not affecting the bsl script on
Linux.
=> Add delay after reset when entering bootloader

cc2538-bsl.py
* Remove pre-emptive calls to `chr`, let `_write` handle this
* Add a check for the error case to catch this more easily in the future
=> Two small Py3k fixes.

cc2538-bsl.py
We have a cc2538-based mote with a Silicon Labs CP2104 USB-to-UART bridge chip. You can find the datasheet in here: https://www.silabs.com/Support%20Documents/TechnicalDocs/cp2104.pdf
In Mac OS X, this chip creates the next type of /dev/tty ports:
```
/dev/tty.SLAB_USBtoUART		
/dev/tty.SLAB_USBtoUART6
```
So, this pull adds SLAB_USBtoUART to the list of possible port names.
=> Add Silicon Labs USB Port Name in Mac OS X

cc2538-bsl.py
This adds CC26xx support in a separate branch `feature/CC26xx_support` until the two can be merged together. This branch will not support CC2538 though.
This branch is little behind master, hence the commits appear in the history here. I _think_ that if you manually move the branch forward to mirror master, the respective commits will disappear from the history here. Happy to rebase if they don't
=> Add CC26xx support

cc2538-bsl.py
It was firing twice, when connecting and reconnecting after clock switching, resetting again the device.With this fix it works fine in mac, but in Linux apparently there is a bug in the drivers for the usb-to-serial chip that we use (CP2104), causing a reset on the RST line whenever a serial connection is opened.
=> Fixed DTR/RTS bootloader

cc2538-bsl.py
If `COMMAND_GET_STATUS` returns anything other than `COMMAND_RET_SUCCESS` (0x40), the script will fail with `ERROR: unhashable type: 'list'`. This is a `TypeError`. This commit fixes this bug.
Reproducing is easy: Simply send a command with a junk address.
Here is an example of broken execution:
```
*** Send Data (0x24)
*** GetStatus command (0x23)
*** received 3 bytes
Traceback (most recent call last):
File "cc2538-bsl.py", line 847, in <module>
if cmd.writeMemory(device.addr_ieee_address_secondary, ieee_addr_bytes):
File "cc2538-bsl.py", line 531, in writeMemory
return self.cmdSendData(data[offs:offs+lng]) # send last data packet
File "cc2538-bsl.py", line 451, in cmdSendData
return self.checkLastCmd()
File "cc2538-bsl.py", line 274, in checkLastCmd
stat_str = RETURN_CMD_STRS.get(stat, …
```
=> Don't fail when `COMMAND_GET_STATUS` signals an error

cc2538-bsl.py
This commit adds the option for the DTR signal to be active high instead of active low. The cc2538 can be configured to accept either. The default remains active low.
=> Added option for active_high_dtr signal

README.md, cc2538-bsl.py
This pull adds support for the CC13xx and CC26xx.
For the CC13xx, we currently only support the 128KB flash variant. In terms of bootloader functionality, protocol etc, the two devices are identical.
More specifically, this pull:
* Introduces chip auto-detection: The CC13xx/CC26xx TRM is quite obscure in terms of the return values of `COMMAND_GET_CHIP_ID`. Therefore, unless the return value matches good old CC2538's  CHIP ID, we assume CC13xx/CC26xx. Seeing some sort of Chip ID in response to said command means we are talking to a device that supports the bootloader's protocol, so not failing for unknown chip IDs makes sense.
* Implements a couple of new commands for the CC13xx/CC26xx (e.g. `COMMAND_BANK_ERASE`)
* Introduces a chip abstraction / class hierarchy.
In terms of this …
=> Add CC13xx and CC26xx support

cc2538-bsl.py
This pull fixes a number of issues with the read functionality:
* We were using `file()`. This is not available with PY3 so we replace it with `open()`.
* `type(length / 4)` is float under PY3, resulting in a `TypeEror`. We change `length / 4` to `length >> 2` so we will always end up with an int. See below:
```
>>> type(4 / 4)
<class 'float'>
>>> type(4 >> 2)
<class 'int'>
```
* The code was expecting `receivePacket()` to return a `str`. This was changed to list (bytes under PY3) a long time ago. We now harmonise `receivePacket()` to always return a bytearray and change the offending code to handle it properly.
Validated by programming a device from a bin file, reading out with `-l 128` and doing a binary comparison between the data read and the first 128 bytes of the original .bin. …
=> Extend read() functionality

cc2538-bsl.py
This pull adds the following:
* Auto-detection of flash size for all supported devices
* Auto-detection of the exact address of the "bootloader disable" byte (changes with flash size)
* Printing of primary IEEE address
* Printing of some other chip info, such as exact member of the CC13xx/CC26xx family, package type, PG versions etc.
The intention is to support all devices, so:
* CC2538: 16/32KB RAM, 128/256/512 flash should all be supported
* CC2630, CC2640, CC2650 should all be supported
* CC1310: F32, F64, F128 should all be supported
* CC1350 should also be supported whenever it gets released
Requires #39 
Closes #5 
This is what it looks like on CC2538 (SmartRF + CC2538EM):
<pre>
$ python cc2538-bsl.py -w -e -v -p /dev/tty.usbserial-00002014B test-firmwares/cc2538.bin 
Opening port …
=> Auto-detect exact chip, flash size, disable bootloader byte offset in CCFG, chip package

README.md, cc2538-bsl.py
This will need rebased, but feel free to have a look at the feature. It is implemented in the last 4 commits of this pull.
Requires `IntelHex` and `python-magic` in site-packages.
With those packages available, we auto-detect the firmware type.
If those packages are not available, support for .hex will be disabled gracefully and the script will still work the way it does ~~not~~ for bin files.
=> Add support for programming from intel hex files

cc2538-bsl.py
As discussed in #13, if the device is running a firmware that prints characters over the UART, those characters will on occasion get buffered. When the bootloader receives the synch sequence (`0x55, 0x55`), those buffered bytes will appear on the host's serial line before the ACK/NACK sequence.
The current version of the script reads 2 bytes when expecting ACK/NACK, and it will therefore fail in the conditions discussed above (since the first 2 bytes received are buffered leftovers instead of an ACK/NACK).
This pull proposes changing `_wait_for_ack` to read byte-by-byte until it encounters ACK/NACK or until it times out.
To reproduce, program the device with a firmware that prints stuff: Contiki's startup sequence will do. Reset the device manually a couple of times and then perform the …
=> Don't fail if the device sends leftover bytes before ACK/NACK

cc2538-bsl.py
Due to bad usage of parentheses, CC2538 RAM size is incorrectly detected as 16KB on 32KB chips.
Sorry about that - back to the basics :S
=> Fix CC2538 RAM size calculation

cc2538-bsl.py
The issue in https://github.com/contiki-os/contiki/issues/1533
Is solved by adding the delay in the "invoke_bootloader" **after** the entire invoking sequence.
=> Fixes issue #1533 on Contiki

cc2538-bsl.py
After merging #50, #48 needs a rebase.
So I've done this rebase, I've removed some trailing whitespaces and excessive new line chars. I've also pythonised the logic that controls which pyserial function to call.
@peretuset @alignan does this work/break anything for you?
Closes #48
=> Add option to invert the bootloader lines (RTS and DTR).

cc2538-bsl.py
As per #52, increase the connect timeout from 0.002 to 0.1 seconds.
This appears to allow enough time for the BSL to start irrespective of
the platform.
=> Increase connect timeout to 0.1 seconds

cc2538-bsl.py
Fix possible wrong die revision, flash memory size, SRAM size, or primary IEEE address.
I have several parts for which `cc2538-bsl` reported a wrong primary IEEE address. Regarding the die revision, the very early parts must have been affected by the issue fixed here. As to the flash memory and SRAM sizes, the cases fixed here do not seem to exist in officially released devices, but they did not match TI's ROM and code, so fix this too in order to avoid any possible current or future issue.
=> Fix CC2538 information

cc2538-bsl.py
CC1310 launchpad shows as ttyACM0 and ttyACM1 when connected via USB. This is on ubuntu 14.04, which is part of the VM bundle that is Instant Contiki.
=> Added 'ttyACM' to list of USB-like names

cc2538-bsl.py
After switching from old v1 to version 2.1 the tool didn't work with two *SmartRF06EB/CC2538EM* kits here anymore. Luckily, with the help of "-V", I found out the my two *CC2538EM* are returning a different chip as expected.
This PR adds the reported id to the dictionary.
After the fix this gorgeous tool works again.
=> cc2538-bsl.py: add new id to CHIP_ID_STRS

cc2538-bsl.py
Fantastically, there are two modules called `python-magic`, both used by importing `magic`, but the two of them have very very incompatible APIs.
The one we are using (and hosted on pypi) is this this one: https://github.com/ahupp/python-magic
The other one ships with libmagic. Some linux installations come with the "wrong" python magic installed. In these python installations, we will encounter this error:
```
Opening port /dev/ttyACM0, baud 500000
Reading data from my_first_app.hex
ERROR: 'module' object has no attribute 'from_file'
```
This pull fixes our behaviour in those installations. python-magic is not critical for the correct operation of this script, so what we do is check (at the time of importing) whether `magic` has an attribute called `from_file`. If it does then we …
=> Don't fall over if the incorrect python-magic gets imported

cc2538-bsl.py
In the latest versions of CC2640 (at least CC2640R2) pg revision number returned has changed to 11 (0x0b). See  "CC13x0, CC26x0 SimpleLinkTM Wireless MCU Technical Reference Manual" (swcu117h.pdf) page 879.
I used "...or pg == 11" instead of setting "pg >= 8" since I have no idea what the versions 9 and 10 are up to.
=> Support for newer CC26xx, CC2640R2 in particular.

cc2538-bsl.py
This allows the serial port to be specified as a remote socket for example
cc2538-bsl.py -p socket://197.228.48.241:2010
=> Added serial_for_url

cc2538-bsl.py
This pull improves detection of CC2640R2 devices. Our current code works for CC2640R2. but fails to correctly report it and also mis-detects the PG version. Both fixed with this pull.
This pull also adds support for some more chip packages
=> Improve support for CC2640R2

README.md, cc2538-bsl.py
Small change on help text when pyserial is missing. pip seems like a better option than macports. Not sure if `pip2` and `pip3` distinction is only made when installing with brew though.
=> Updated help text when pyserial is missing

cc2538-bsl.py
The `--version` option didn't look that good in python3, this fixes it. Also changed to `__version__` naming for the version string.
The whole _get the version string from git_ isn't working as well as I intended it to since for example [RIOT](https://github.com/RIOT-OS/RIOT) is just copying the script into their source instead of using submodules (I tried convincing them). So `--version` just gives the version of their main git repo instead of the actual version of this script.
Any ideas to improve the version string, except for just hard-coding it.
=> made --version option python3 compatible

cc2538-bsl.py
Python 3.8+ will emit a SyntaxWarning when `is` or `is not` is used. This PR replaces them accordingly. 
Log when `is`/`is not` is used:
```
➜ python3 cc2538-bsl.py -p /dev/tty.usbserial-1420 -evw ~/Desktop/znp_CC26X2R1_LAUNCHXL_tirtos_ccs.hex
/Users/Koenkk/Git/cc2538-bsl/cc2538-bsl.py:971: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if int(value) % int(device.page_size) is not 0:
/Users/Koenkk/Git/cc2538-bsl/cc2538-bsl.py:976: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if int(value, 16) % int(device.page_size) is not 0:
Opening port /dev/tty.usbserial-1420, baud 500000
Reading data from /Users/Koenkk/Desktop/znp_CC26X2R1_LAUNCHXL_tirtos_ccs.hex
Your firmware looks like an Intel Hex file
Connecting to target...
```
Ref: …
=> Fix SyntaxWarning when running with Python 3.8+

cc2538-bsl.py
Disallow the script to hang forever if the serial fails to write.
How to reproduce: Try to flash a device without connecting it to the serial port.
- Before this PR: Script will hang forever.
- After this PR: Script will hang for 10 seconds.
The serial port contains a `timeout` attribute on construction.
During a test, I noticed the script stuck as if ignoring the `timeout`.
Discovered that `timeout` is for reading, but there is a `write_timeout` attribute as well, which is required not to hang if the device does not _acks_ the write.
Source 1: [PySerial docs](https://pyserial.readthedocs.io/en/latest/pyserial_api.html)
Source 2: [Related Stack Overflow question](https://stackoverflow.com/questions/39032581/python-serial-write-timeout)
Added `write_timeout` attribute to serial port …
=> add write_timeout to serial port

cc2538-bsl.py
This PR adds support for the Itead Sonoff CC2652P usb dongle (https://itead.cc/product/sonoff-zigbee-3-0-usb-dongle-plus/) with the new option `--bootloader-sonoff-usb`.
With this new option you don't have to manually start the bootloader with the 2 buttons on the PCB anymore.
This dongle does not have a 1 to 1 connection between RTS DTR and RST IO15, but uses 2 NPN transistors to connect them together with the following truth table:
```
DTR  RTS  |  RST  IO15
1     1   |   1    1
0     0   |   1    1
1     0   |   0    1
0     1   |   1    0
```
I'm not aware of any other HW that uses this connection, so I'm naming the option after the specific hardware. In the future this should probably get a more general name like `--bootloader-imply-gate` or something. (the truth table is an imply …
=> Add Itead Sonoff CC2652P usb stick bootloader invoke toggle

cc2538-bsl.py
This PR takes a similar approach as initially taken in  #87, I finally still find useful to let the script deal with finding out what sections need to be erased. So here I added the following option:
```
-W, --write-erase will erase flash pages where data will be written,
this avoids performing a mass erase.
```
=> cc2538-bsl: add -W,--write-erase to write and erase

README.md
Update README.md documenting new `--bootloader-sonoff-usb` option from https://github.com/JelmerT/cc2538-bsl/pull/114
Note that @JelmerT mentioned in https://github.com/JelmerT/cc2538-bsl/pull/114 that option might be renamed to `--bootloader-imply-gate` in the future, see comment:
> This PR adds support for the Itead Sonoff CC2652P usb dongle (https://itead.cc/product/sonoff-zigbee-3-0-usb-dongle-plus/) with the new option `--bootloader-sonoff-usb`. With this new option you don't have to manually start the bootloader with the 2 buttons on the PCB anymore.
> 
> This dongle does not have a 1 to 1 connection between RTS DTR and RST IO15, but uses 2 NPN transistors to connect them together with the following truth table:
> 
> ```
> DTR  RTS  |  RST  IO15
> 1     1   |   1    1
> 0     0   | …
```
=> Update README.md documenting bootloader-sonoff-usb

README.md
This is a request to adding a link to the Docker documentation (see https://github.com/JelmerT/cc2538-bsl/issues/120).
=> Add link to Docker documentation

setup.py
`pip`, `setuptools`, and `wheel` are not depended upon by the source code.
=> Clean up unnecessary install dependencies

cc2538-bsl.py
I have kept any changes not directly related to argparse out of this PR. However, switching to it should allow a lot more code cleaning in the future.
=> Switch to argparse

cc2538-bsl.py
Fix for https://github.com/JelmerT/cc2538-bsl/issues/161
=> Fix broken `port` arg

cc2538-bsl.py
Fix for https://github.com/JelmerT/cc2538-bsl/issues/162#issuecomment-2004919839
=> fix: handle missing ieee_address

cc2538-bsl.py
Fixes #137 by raising timeout values acceptable for flashing over LAN.
=> Raising timeouts for operation over LAN.

cc2538-bsl.py
newer versions of magic from file_open now detect the hex file as `text/x-hex` instead of `text/plain`
=> fix: improve compatibility with newer file magic detection
